services:
    koco.kafka.factory:
        class: 'Koco\Kafka\Messenger\KafkaTransportFactory'
        arguments:
            - '@Psr\Log\LoggerInterface'
        tags: ['messenger.transport_factory']
