version: 2.1
orbs:
  wait-for: cobli/wait-for@0.0.2
jobs:
  build:
    working_directory: ~/messenger-kafka
    docker:
      - image: circleci/php:7.4.4
      - image: lensesio/fast-data-dev
        environment:
          SAMPLEDATA: 0
          RUNTESTS: 0
          FORWARDLOGS: 0

    steps:
      - checkout

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo apt install librdkafka1 librdkafka-dev kafkacat netcat
      - run: sudo docker-php-ext-install zip && sudo pecl install rdkafka && sudo docker-php-ext-enable rdkafka

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            # - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-latest

      - run: composer install -n --prefer-dist

      # Pull Simple PHPUnit dependencies
      - run: ./vendor/bin/simple-phpunit --version

      - save_cache:
          key: v1-dependencies-latest
          paths:
            - ./vendor
            - ./vendor/bin/.phpunit/phpunit-8.3-0/vendor

      # Wait for the Kafka container
      - wait-for/kafka

      # Test
      - run: mkdir results && mkdir results/tests && ./vendor/bin/simple-phpunit --log-junit results/tests/junit.xml --coverage-html results/coverage-report

      - store_test_results:
          path: ~/messenger-kafka/results/

      - store_artifacts:
          path:  ~/messenger-kafka/results/coverage-report